export const SHOW_LOADER = 'SHOW_LOADER';
export const SAVE_SEARCH_TYPE_AND_RESULTS = 'SAVE_SEARCH_TYPE_AND_RESULTS';
export const SHOW_TOAST = 'SHOW_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';